"""empty message

Revision ID: 0b124d57c284
Revises: 
Create Date: 2024-12-12 09:57:32.589099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b124d57c284'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('clasificacion', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('orden', sa.Float(), nullable=True),
    sa.Column('padre', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parametros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedores_calificados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('nrc', sa.String(length=50), nullable=False),
    sa.Column('nit', sa.String(length=50), nullable=True),
    sa.Column('min_factoring', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_factoring', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cuenta_bancaria', sa.String(length=255), nullable=True),
    sa.Column('nombre_contacto', sa.String(length=255), nullable=True),
    sa.Column('correo_electronico', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_factura', sa.String(length=50), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=False),
    sa.Column('fecha_vence', sa.DateTime(), nullable=False),
    sa.Column('fecha_otorga', sa.DateTime(), nullable=False),
    sa.Column('dias_credito', sa.Integer(), nullable=False),
    sa.Column('nombre_proveedor', sa.String(length=255), nullable=True),
    sa.Column('nit', sa.String(length=50), nullable=True),
    sa.Column('noti_cliente', sa.String(length=1), nullable=False),
    sa.Column('noti_contador', sa.String(length=1), nullable=False),
    sa.Column('factura_hash', sa.String(length=255), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores_calificados.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_menu', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_menu'], ['menus.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=255), nullable=False),
    sa.Column('apellidos', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('temp_password', sa.String(length=255), nullable=True),
    sa.Column('cargo', sa.String(length=255), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('token_date_end', sa.DateTime(), nullable=True),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('reg_activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bitacoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=255), nullable=True),
    sa.Column('modulo', sa.String(length=255), nullable=True),
    sa.Column('accion', sa.String(length=255), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('exito', sa.Boolean(), nullable=True),
    sa.Column('tipo', sa.Enum('bitacora', 'alerta'), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitudes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_cliente', sa.String(length=255), nullable=False),
    sa.Column('contacto', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('descuento_app', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cargo', sa.String(length=255), nullable=True),
    sa.Column('iva', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('id_estado', sa.Integer(), nullable=True),
    sa.Column('id_factura', sa.Integer(), nullable=True),
    sa.Column('id_aprobador', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_aprobador'], ['usuarios.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_estado'], ['estados.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_factura'], ['facturas.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.Column('id_factura', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_factura'], ['facturas.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitudes.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('desembolsos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_desembolso', sa.DateTime(), nullable=False),
    sa.Column('monto_final', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=255), nullable=True),
    sa.Column('cuenta_bancaria', sa.String(length=255), nullable=True),
    sa.Column('no_transaccion', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitudes.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('desembolsos')
    op.drop_table('comentarios')
    op.drop_table('solicitudes')
    op.drop_table('bitacoras')
    op.drop_table('usuarios')
    op.drop_table('permisos')
    op.drop_table('facturas')
    op.drop_table('roles')
    op.drop_table('proveedores_calificados')
    op.drop_table('parametros')
    op.drop_table('menus')
    op.drop_table('estados')
    # ### end Alembic commands ###
